// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDf2Tj_C_dD76ic0G5xpoBpsbqsTYB8rk4",
    authDomain: "festit-c0636.firebaseapp.com",
    projectId: "festit-c0636",
    storageBucket: "festit-c0636.appspot.com",
    messagingSenderId: "133375235827",
    appId: "1:133375235827:web:502384859e425e2f17c986",
    measurementId: "G-Q41DKM8WLN",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsQQwh3FXhkb0pevQHZ3tQSmANyLTf2x0',
    appId: '1:133375235827:android:bcbedac8ff5be33217c986',
    messagingSenderId: '133375235827',
    projectId: 'festit-c0636',
    storageBucket: 'festit-c0636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlCimDz_kRRwcbySTemlBfjj4WKXe7QLs',
    appId: '1:133375235827:ios:8bdb722dcfdfdfed17c986',
    messagingSenderId: '133375235827',
    projectId: 'festit-c0636',
    storageBucket: 'festit-c0636.appspot.com',
    iosBundleId: 'com.example.festitInvited',
  );
}
